version: '3.1'
services:
  nexus:
    image: sonatype/nexus3:3.61.0
    container_name: nexus_3_61 
    restart: always
    environment:
       # Nexus 上下文路径
       NEXUS_CONTEXT: /
       # 指定jvm参数
       INSTALL4J_ADD_VM_PARAMS: -Xms1g -Xmx1g -XX:MaxDirectMemorySize=3g
    volumes:
    # 需要先给权限 chown -R 200 ./data
    - ./data:/nexus-data
    ports:
      - "8081:8081"
      
    networks:
      - devopsnetwork

networks:
  devopsnetwork:
    external: true
