version: '3.1'
services:
  redis:
    container_name: cluster_redis_6381
    image: redis:6.2.13
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6381:6381"
      - "16381:16381"
    networks:
      - devopsnetwork

networks:
  devopsnetwork:
    external: true
