version: '3.1'
services:
  dns:
    image: sameersbn/bind:9.16.1-20200524
    container_name: dns_9_16
    restart: always
    environment:
      TZ : 'Asia/Shanghai'
      ROOT_PASSWORD: devops666
      WEBMIN_ENABLED: true
      # 默认 true https://ip:10000
      WEBMIN_INIT_SSL_ENABLED: true
    ports:
        - '10000:10000/tcp'
        - '53:53/udp'
        - '53:53/tcp'
    volumes:
      - ./data:/data
    networks:
      - devopsnetwork

networks:
  devopsnetwork:
    external: true
